ibm-locks: shut up clang-tidy by disabling code
There is code in ibm/locks that has had clang-tidy warnings disabled
for a while due to multiple safety and endianness issues.  The code
has not been fixed in a while and with clang-16 it is unable to be
exempted further.  Disable it until someone who cares can fix this
in the proper way.

```
../include/ibm/locks.hpp:522:14: error: 'p' is an unsafe pointer used for buffer access [-Werror,-Wunsafe-buffer-usage]
    uint8_t* p = reinterpret_cast<uint8_t*>(&resourceId1);
    ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../include/ibm/locks.hpp:527:25: note: used in buffer access here
    uint8_t pPosition = p[position];
                        ^
../include/ibm/locks.hpp:524:14: error: 'q' is an unsafe pointer used for buffer access [-Werror,-Wunsafe-buffer-usage]
    uint8_t* q = reinterpret_cast<uint8_t*>(&resourceId2);
    ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../include/ibm/locks.hpp:529:25: note: used in buffer access here
    uint8_t qPosition = q[position];
```

Signed-off-by: Patrick Williams <patrick@stwcx.xyz>
Change-Id: I8a7fcbed1099419ad1715c86ffcbfef20820251e