Update patch set 3
Patch Set 3:

> Patch Set 2:
> 
> Strange, i didn't hit this warning/error when i ran CI locally.
> 
> ../http/utility.hpp:423:25: error: either cast from 'int' to 'size_t' (aka 'unsigned long') is ineffective, or there is loss of precision before the conversion [bugprone-misplaced-widening-cast,-warnings-as-errors]
>             *it++ = key[static_cast<size_t>(((data[i + 0] & 0x03) << 4) +
>                         ^

Locally you're building as 32 bit (probably) and the build server is building as 64 bit, hence this error.

Patch-set: 3
Reviewer: Gerrit User 1000153 <1000153@adbd0a64-1f21-4d83-b585-671fe73cb6e4>