Remove code using ambiguous privileges constructor
432a890c removed the ambiguous privileges constructor.
af61db10 added code that used this removed ambiguous privileges
constructor.

This is causing bmcweb CI and bmcweb autobumps to fail.

The error looks like:
error: cannot convert '<brace-enclosed initializer list>' to 'const
std::initializer_list<std::initializer_list<const char*> >&'
|  3102 |         .privileges({"Login"})

af61db10 passed CI because it was pushed before and based on a parent
that was before 432a890c.

Tested: bmcweb builds. No further testing done.
Change-Id: I21399033d63851e3c83f3cd5a00e1227064e6941
Signed-off-by: Gunnar Mills <gmills@us.ibm.com>