Make time_utils tests compile on clang
This mechanism usees some very complex parameterization for tests, and
unfortunately fails to compile on clang with a:
../../../../../../workspace/sources/bmcweb/redfish-core/ut/time_utils_test.cpp:13:1:
error: identifier 'gtest__FromDurationTest_EvalGenerator_' is reserved
because it contains '__' [-Werror,-Wreserved-identifier]

Fortunately, there's a much simpler way to write this test, simply
calling EXPECT_EQ for the inputs like we do other places.

Tested: Unit tests now compile in clang.  Unit tests run in CI.

Signed-off-by: Ed Tanous <edtanous@google.com>
Change-Id: I271c43b773feecefaa28940db47513c9465765a4