meson: Disable tests build for tinyxml2 dependency
Currently local meson build breaks on tinyxml2 since the code from
this package produces a warning and all warnings are treated as errors:
"""
../subprojects/tinyxml2-9.0.0/xmltest.cpp:711:38: error: ignoring
return value of ‘char* fgets(char*, int, FILE*)’ declared with
attribute ‘warn_unused_result’ [-Werror=unused-result]
"""
The warning above comes from the compilation of the tinyxml2 unit tests.
Since we don't really need them, disable 'tests' option for tinyxml2
dependency to fix the meson build.

Tested:
Locally executed "meson setup build && cd build && meson compile" now
finishes successfully.

Change-Id: I7148856a3eebbda22d03c9715955b6ab78a933fe
Signed-off-by: Konstantin Aladyshev <aladyshev22@gmail.com>