Fix clang-tidy issue in aggregation
clang-tidy flags the following error, which is correct.

```
../redfish-core/include/query.hpp:145:26: error: static member accessed through instance [readability-static-accessed-through-instance,-warnings-as-errors]
    needToCallHandlers = RedfishAggregator::getInstance().beginAggregation(
```

Tested (Carson):
Verified that queries to top level collections as well as aggregated
resources still return as expected.

Signed-off-by: Ed Tanous <edtanous@google.com>
Change-Id: I440fb29d2e0b3da52bfd564676d33b72f69f2fbc
Signed-off-by: Carson Labrado <clabrado@google.com>