subprojects: nlohmann-json: update to 3.11.3
3.11.2 has a bug where it does not generate `json_fwd.hpp`, which
is required by sdbusplus.  This is fixed in 3.11.3.  Use `meson wrap
update nlohmann_json` to get the latest WrapDB version.

Tested:

Using the base Docker container from openbmc-build-scripts, previously
there was the following compile issue:

```
In file included from ../subprojects/sdbusplus/include/sdbusplus/bus.hpp:6,
                 from ../subprojects/sdbusplus/src/bus.cpp:1:
../subprojects/sdbusplus/include/sdbusplus/exception.hpp:5:10: fatal error: nlohmann/json_fwd.hpp: No such file or directory
    5 | #include <nlohmann/json_fwd.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~
```

This is resolved now.

Signed-off-by: Patrick Williams <patrick@stwcx.xyz>
Change-Id: I6e30bf10f1b5ef4b0424b39314c9dcfb718cd890