time-utils: fix clang-tidy warning
The code already does size checking to ensure that buffer overruns
are not done, so switch to using operator[] rather than pointer
arithmetic.

```
../redfish-core/include/utils/time_utils.hpp:71:19: error: unsafe pointer arithmetic [-Werror,-Wunsafe-buffer-usage]
        end = fmt.data() + pos;
```

Signed-off-by: Patrick Williams <patrick@stwcx.xyz>
Change-Id: Iaabe82d7c1621dc27ad10288732609dfd0516d17