Update patch set 18
Patch Set 18:

> > Patch Set 18:
 > >
 > > > > Patch Set 18:
 > >  > >
 > >  > > > > Patch Set 18:
 > >  > >  > >
 > >  > >  > > Hi Ed, I tried the protocol_type overload for the
 > >  > async_resolve ,
 > >  > >  > but no luck on that as well.
 > >  > >  >
 > >  > >  > Understood.  You might consider starting with the beast
 > async
 > >  > >  > example here:
 > >  > >  > https://github.com/boostorg/beast/blob/develop/example/http/client/async/http_client_async.cpp
 > >  > >  >
 > >  > >  > then slowly move toward the code you're using, and see at
 > what
 > >  > >  > point it breaks.
 > >  > >
 > >  > > I copied this async client file as http/http_async_client.hpp.
 > >  > > Made changes in the subscriber to create this client object
 > when
 > >  > a subscription is made.
 > >  > > Moved some basic functionalities from the existing https
 > client
 > >  > to this new client to get the compilation through.
 > >  > > I found this is crashing with at the async_resolve
 > >  > >
 > >  > > @Apparao - can you help here to check if the async_resolve
 > works?
 > >  >
 > >  > Does http_client_async.cpp work on its own when built for the
 > bmc
 > >  > with no changes, and outside of bmcweb?
 > >
 > > Firstly i am sorry for late pitch in here. I see modifications
 > made here to improve and address the comments. Thank you so much.
 > >
 > > No http
 > >
 > >  > > Patch Set 18:
 > >  > >
 > >  > > > > Patch Set 18:
 > >  > >  > >
 > >  > >  > > Hi Ed, I tried the protocol_type overload for the
 > >  > async_resolve ,
 > >  > >  > but no luck on that as well.
 > >  > >  >
 > >  > >  > Understood.  You might consider starting with the beast
 > async
 > >  > >  > example here:
 > >  > >  > https://github.com/boostorg/beast/blob/develop/example/http/client/async/http_client_async.cpp
 > >  > >  >
 > >  > >  > then slowly move toward the code you're using, and see at
 > what
 > >  > >  > point it breaks.
 > >  > >
 > >  > > I copied this async client file as http/http_async_client.hpp.
 > >  > > Made changes in the subscriber to create this client object
 > when
 > >  > a subscription is made.
 > >  > > Moved some basic functionalities from the existing https
 > client
 > >  > to this new client to get the compilation through.
 > >  > > I found this is crashing with at the async_resolve
 > >  > >
 > >  > > @Apparao - can you help here to check if the async_resolve
 > works?
 > >  >
 > >  > Does http_client_async.cpp work on its own when built for the
 > bmc
 > >  > with no changes, and outside of bmcweb?
 > >
 > > Firstly i am sorry for late pitch in here. I see modification
 > made here to improve and address comments on this. Thank you so
 > much for it.
 > >
 > > Ed, I tried http_client_async.cpp directly as standalone (before
 > 8 months back) and its crashes at async_resolve(). There seems to
 > be issue with async_resolve() in beast library.
 > >
 > > With latest changes, I see some state machine is not handled
 > properly and causing crashes. I started looking into it and will
 > upload new patch set with it.
 > 
 > I just tried this on my machine for both the SSL example and the
 > http example
 > 
 > wget https://raw.githubusercontent.com/boostorg/beast/develop/example/http/client/async/http_client_async.cpp
 > 
 > sudo apt install libboost1.71-all-dev
 > g++ --std=c++17 http_client_async.cpp -I /usr/include -L /usr/lib/
 > -lboost_system -lboost_thread -lpthread
 > 
 > ./a.out www.google.com 80 /
 > 
 > Resolves dns properly, and works as designed, loading the page. 
 > The same goes for the SSL example.  Can you clarify what test you
 > ran?
 > 
 > 1. Something is broken in the arm specific build.
 > 2. Something is broken in dns resolution on OpenBMC.
 > 
 > Next step is to start taking the working example, and move it to
 > the bmc as-is, and verify if it works correctly.  That will give
 > you next steps.

Last time (Few months back) when i built the http_client_async.cpp as is(standalone), I saw had seen the crash like below.
./http-client-async <server> 5002 /
terminate called after throwing an instance of 'boost::wrapexcept<boost::system::system_error>'
  what():  thread: Operation not supported


Further checking i figured it out that "-DBOOST_ASIO_DISABLE_THREADS"  definition in cmake is causing the issue.

I enabled Boost.asio's threading support and "http_client_async.cpp" works fine(able to resolve the dns). Its done on standalone build x86 arch.

./http-client-async <server> 5002 /
HTTP/1.0 200 OK
Server: BaseHTTP/0.6 Python/3.5.2
Date: Thu, 03 Dec 2020 16:31:57 GMT

GET request Ack from server!

So issue is when we explicitly disable Boost.asio's threading support(I.e -DBOOST_ASIO_DISABLE_THREADS). Enabling this boost.asio has other compile issue on bmcweb(I think this is disabled purposefully for to using asio threads in bmcweb repo). 
Compile errors:
/usr/include/boost/asio/detail/impl/posix_thread.ipp:35: undefined reference to `pthread_detach'
/usr/include/boost/asio/detail/impl/posix_thread.ipp:59: undefined reference to `pthread_create'
/usr/include/boost/asio/detail/impl/posix_thread.ipp:42: undefined reference to `pthread_join'
/usr/include/boost/asio/detail/posix_signal_blocker.hpp:50: undefined reference to `pthread_sigmask'

.........

Can we enable boost.asio threads support in bmcweb and link associated libraries for avoid above compilation issues? Any suggestions?

Patch-set: 18
Reviewer: Gerrit User 1000269 <1000269@adbd0a64-1f21-4d83-b585-671fe73cb6e4>
Label: Code-Review=0