http-logging: fix clang-tidy warnings
```
/data0/jenkins/workspace/ci-repository/openbmc/bmcweb/http/logging.hpp:132:9: error: macro is not used [clang-diagnostic-unused-macros,-warnings-as-errors]
 #define BMCWEB_LOG_CRITICAL
```

Add NOLINTBEGIN/NOLINTEND guards around the whole of the macro
definitions because there are now multiple clang-tidy warning types
that call out this behavior, but we want it in this case.

Signed-off-by: Patrick Williams <patrick@stwcx.xyz>
Change-Id: Iac2ee839999f36424ca6dfed212d0bad0a2f3ae5