WIP: Enable port 18080
The commit [1] altered how sockets are created and removed the
default port 18080. We use this port extensively in development.
The bmcweb documentation describes the port 18080 for this use. [2]
There are unit tests that also use this port although I'm not seeing the
handle() function being utilized. [3] We would like this port to be
available by default.

The commit [1] added meson build options for adding additional ports.
In attempting to enable port 18080 I ran into various build errors when
additional-ports has a value. I've corrected the config/meson.build file
to address those errors.

Note: Meson defines arrays as containing strings so there is no
to_string() method for the array member. [4]
```
../../../../../../workspace/sources/bmcweb/config/meson.build:137:39: ERROR: Unknown method "to_string" in object <[StringHolder] holds [str]: '18080'> of type StringHolder.
```

Additional recipe changes were needed to add bmcweb_18080 to
SYSTEMD_SERVICE to address errors seen in build during packaging.
```
 ERROR: bmcweb-1.0+git-r0 do_package: QA Issue: bmcweb: Files/directories were installed but not shipped in any package:
  /usr/lib/systemd/system/bmcweb_18080
```

Tested: WIP

[1] https://gerrit.openbmc.org/c/openbmc/bmcweb/+/35265
[2] https://github.com/openbmc/bmcweb/blob/cc67d0a0fed101c930b334a583d9ca9b222ceb77/TESTING.md?plain=1#L57
[3] https://github.com/openbmc/bmcweb/blob/cc67d0a0fed101c930b334a583d9ca9b222ceb77/test/http/http2_connection_test.cpp#L56
[4] https://mesonbuild.com/Build-options.html#arrays

Change-Id: Ia1b326bedca808e43e73ce2b241178bc4bfab23c
Signed-off-by: Janet Adkins <janeta@us.ibm.com>