ssl: remove BMCWEB_ENABLE_SSL since openssl is not optional anymore
With `BMCWEB_ENABLE_SSL`, it will cause issues that depends on
`ensuressl`. Since openssl is required, that flag can be removed for the
ssl_key_handler.

prepareMutualTls() is dependent on `ensuressl` which is only available
`insecure-disable-ssl` is disable so the CI didn't catch this error.

If `insecure-disable-ssl` is enable, then `ensuressl` will be missing
and fail the bmcweb build due to prepareMutualTls().

Error example,
```
Step #1: In file included from ../git/http/http_server.hpp:3,
Step #1:                  from ../git/http/app.hpp:5,
Step #1:                  from ../git/src/webserver_main.cpp:4:
Step #1: ../git/http/http_connection.hpp: In member function 'void crow::Connection<Adaptor, Handler>::prepareMutualTls()':
Step #1: ../git/http/http_connection.hpp:99:38: error: 'ensuressl' has not been declared
Step #1:    99 |         std::filesystem::path caPath(ensuressl::trustStorePath);
Step #1:       |                                      ^~~~~~~~~
Step #1: ninja: build stopped: subcommand failed.
```

Change-Id: I3c010d5042b4615623b1c043a368ba5c9cbc6b4c
Signed-off-by: Willy Tu <wltu@google.com>