Skip CSRF token check for BasicAuth
The "Sec-WebSocket-Protocol" is used in token based authentication
methods for mitigating the CSRF attacks. Where clients can read the
generated CSRF tokens in webserver by reading response header
"Sec-WebSocket-Protocol" and can fill in the token value as request
header for subsequent requests. But in case of BasicAuth, its not a
valid case. So added property in session object to indentify the
authentication method and skip the CSRF token verification.

Sec-Websocket-Protocol: onBIZJsIdeWUvRBO9MeX

The 401 unauthorized request issue is observed when establishing the
websockets(SOL) communication using basicAuth (via python).
Error: server rejected WebSocket connection: HTTP 401

Since webui uses the token based authentication, and it fills the
"Sec-Websocket-Protocol", This issue is not observed with webui.
https://github.com/openbmc/webui-vue/blob/b63e9d9a70dabc4c9a7038f7727fca6bd17d940a/src/views/Operations/SerialOverLan/SerialOverLanConsole.vue#L98

This issue is introduced while cleaning up websocket csrf
specific code.
https://gerrit.openbmc.org/c/openbmc/bmcweb/+/62135

Tested:
- SOL communication works fine with BasicAuth.
- SOL communication works with webui and CSRF is verified.

Change-Id: I39de2e9e49a3bce96e500310e0337613d39f81f1
Signed-off-by: AppaRao Puli <apparao.puli@intel.com>