multipart-parser: use emplace_back
clang-17 will have a stronger 'modernize-use-emplace' check and
fails with the following warning:

```
../include/multipart_parser.hpp:308:33: error: use emplace_back instead of push_back [modernize-use-emplace,-warnings-as-errors]
  308 |                     mime_fields.push_back({});
      |                                 ^~~~~~~~~~~~
      |                                 emplace_back(
```

The vector::emplace_back needed an extra hint, as it would not directly
coerce an initializer-list into the vector's value_type, so we need to
use the value_type constructor.

Signed-off-by: Patrick Williams <patrick@stwcx.xyz>
Change-Id: I74417e0ff5a6e0991bfbe4936b4814f6ee4c1269