Fix build with rest option disabled
When the rest option is disabled the build fails with the following
error:
ERROR: Unknown variable "tinyxml".

This change defines the tinyxml dependency outside of the rest
option, so it always exists.

Change-Id: Id392dd068902643cf90ec135733c31bf265bf75f
Signed-off-by: Jason M. Bills <jason.m.bills@linux.intel.com>